/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeddingsRouteImport } from './routes/weddings'
import { Route as StoryRouteImport } from './routes/story'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ReserveRouteImport } from './routes/reserve'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as AccommodationsRouteImport } from './routes/accommodations'
import { Route as IndexRouteImport } from './routes/index'

const WeddingsRoute = WeddingsRouteImport.update({
  id: '/weddings',
  path: '/weddings',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ReserveRoute = ReserveRouteImport.update({
  id: '/reserve',
  path: '/reserve',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const AccommodationsRoute = AccommodationsRouteImport.update({
  id: '/accommodations',
  path: '/accommodations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accommodations': typeof AccommodationsRoute
  '/menu': typeof MenuRoute
  '/reserve': typeof ReserveRoute
  '/reviews': typeof ReviewsRoute
  '/story': typeof StoryRoute
  '/weddings': typeof WeddingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accommodations': typeof AccommodationsRoute
  '/menu': typeof MenuRoute
  '/reserve': typeof ReserveRoute
  '/reviews': typeof ReviewsRoute
  '/story': typeof StoryRoute
  '/weddings': typeof WeddingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accommodations': typeof AccommodationsRoute
  '/menu': typeof MenuRoute
  '/reserve': typeof ReserveRoute
  '/reviews': typeof ReviewsRoute
  '/story': typeof StoryRoute
  '/weddings': typeof WeddingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accommodations'
    | '/menu'
    | '/reserve'
    | '/reviews'
    | '/story'
    | '/weddings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accommodations'
    | '/menu'
    | '/reserve'
    | '/reviews'
    | '/story'
    | '/weddings'
  id:
    | '__root__'
    | '/'
    | '/accommodations'
    | '/menu'
    | '/reserve'
    | '/reviews'
    | '/story'
    | '/weddings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccommodationsRoute: typeof AccommodationsRoute
  MenuRoute: typeof MenuRoute
  ReserveRoute: typeof ReserveRoute
  ReviewsRoute: typeof ReviewsRoute
  StoryRoute: typeof StoryRoute
  WeddingsRoute: typeof WeddingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weddings': {
      id: '/weddings'
      path: '/weddings'
      fullPath: '/weddings'
      preLoaderRoute: typeof WeddingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserve': {
      id: '/reserve'
      path: '/reserve'
      fullPath: '/reserve'
      preLoaderRoute: typeof ReserveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accommodations': {
      id: '/accommodations'
      path: '/accommodations'
      fullPath: '/accommodations'
      preLoaderRoute: typeof AccommodationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccommodationsRoute: AccommodationsRoute,
  MenuRoute: MenuRoute,
  ReserveRoute: ReserveRoute,
  ReviewsRoute: ReviewsRoute,
  StoryRoute: StoryRoute,
  WeddingsRoute: WeddingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
