/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeddingsRouteImport } from './routes/weddings'
import { Route as StoryRouteImport } from './routes/story'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ReserveRouteImport } from './routes/reserve'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as InnRouteImport } from './routes/inn'
import { Route as FarmsteadRouteImport } from './routes/farmstead'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AccommodationsRouteImport } from './routes/accommodations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogManageRouteImport } from './routes/blog.manage'

const WeddingsRoute = WeddingsRouteImport.update({
  id: '/weddings',
  path: '/weddings',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ReserveRoute = ReserveRouteImport.update({
  id: '/reserve',
  path: '/reserve',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const InnRoute = InnRouteImport.update({
  id: '/inn',
  path: '/inn',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmsteadRoute = FarmsteadRouteImport.update({
  id: '/farmstead',
  path: '/farmstead',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AccommodationsRoute = AccommodationsRouteImport.update({
  id: '/accommodations',
  path: '/accommodations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogManageRoute = BlogManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accommodations': typeof AccommodationsRoute
  '/blog': typeof BlogRouteWithChildren
  '/farmstead': typeof FarmsteadRoute
  '/inn': typeof InnRoute
  '/menu': typeof MenuRoute
  '/reserve': typeof ReserveRoute
  '/reviews': typeof ReviewsRoute
  '/story': typeof StoryRoute
  '/weddings': typeof WeddingsRoute
  '/blog/manage': typeof BlogManageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accommodations': typeof AccommodationsRoute
  '/blog': typeof BlogRouteWithChildren
  '/farmstead': typeof FarmsteadRoute
  '/inn': typeof InnRoute
  '/menu': typeof MenuRoute
  '/reserve': typeof ReserveRoute
  '/reviews': typeof ReviewsRoute
  '/story': typeof StoryRoute
  '/weddings': typeof WeddingsRoute
  '/blog/manage': typeof BlogManageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accommodations': typeof AccommodationsRoute
  '/blog': typeof BlogRouteWithChildren
  '/farmstead': typeof FarmsteadRoute
  '/inn': typeof InnRoute
  '/menu': typeof MenuRoute
  '/reserve': typeof ReserveRoute
  '/reviews': typeof ReviewsRoute
  '/story': typeof StoryRoute
  '/weddings': typeof WeddingsRoute
  '/blog/manage': typeof BlogManageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accommodations'
    | '/blog'
    | '/farmstead'
    | '/inn'
    | '/menu'
    | '/reserve'
    | '/reviews'
    | '/story'
    | '/weddings'
    | '/blog/manage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accommodations'
    | '/blog'
    | '/farmstead'
    | '/inn'
    | '/menu'
    | '/reserve'
    | '/reviews'
    | '/story'
    | '/weddings'
    | '/blog/manage'
  id:
    | '__root__'
    | '/'
    | '/accommodations'
    | '/blog'
    | '/farmstead'
    | '/inn'
    | '/menu'
    | '/reserve'
    | '/reviews'
    | '/story'
    | '/weddings'
    | '/blog/manage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccommodationsRoute: typeof AccommodationsRoute
  BlogRoute: typeof BlogRouteWithChildren
  FarmsteadRoute: typeof FarmsteadRoute
  InnRoute: typeof InnRoute
  MenuRoute: typeof MenuRoute
  ReserveRoute: typeof ReserveRoute
  ReviewsRoute: typeof ReviewsRoute
  StoryRoute: typeof StoryRoute
  WeddingsRoute: typeof WeddingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weddings': {
      id: '/weddings'
      path: '/weddings'
      fullPath: '/weddings'
      preLoaderRoute: typeof WeddingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserve': {
      id: '/reserve'
      path: '/reserve'
      fullPath: '/reserve'
      preLoaderRoute: typeof ReserveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inn': {
      id: '/inn'
      path: '/inn'
      fullPath: '/inn'
      preLoaderRoute: typeof InnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmstead': {
      id: '/farmstead'
      path: '/farmstead'
      fullPath: '/farmstead'
      preLoaderRoute: typeof FarmsteadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accommodations': {
      id: '/accommodations'
      path: '/accommodations'
      fullPath: '/accommodations'
      preLoaderRoute: typeof AccommodationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/manage': {
      id: '/blog/manage'
      path: '/manage'
      fullPath: '/blog/manage'
      preLoaderRoute: typeof BlogManageRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogManageRoute: typeof BlogManageRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogManageRoute: BlogManageRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccommodationsRoute: AccommodationsRoute,
  BlogRoute: BlogRouteWithChildren,
  FarmsteadRoute: FarmsteadRoute,
  InnRoute: InnRoute,
  MenuRoute: MenuRoute,
  ReserveRoute: ReserveRoute,
  ReviewsRoute: ReviewsRoute,
  StoryRoute: StoryRoute,
  WeddingsRoute: WeddingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
